# string = input('Введіть текст:')
# kilkist = int(input('Введіть число:'))
# print(string.capitalize() * kilkist)
# print(string.upper() * kilkist)
# print(string.lower() * kilkist)
my_str = input('Введіть рядок: ')
print(my_str)
kilkist_povtoriv = int(input('Введіть число: '))
print(my_str * kilkist_povtoriv)
print(my_str.upper())
print(my_str.lower())
print(my_str.title())
print(my_str.capitalize())
